# Generated by Django 5.2.17 on 2026-09-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "external_id",
                    models.PositiveIntegerField(
                        verbose_name="Внешний ID товара у поставщика"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Артикул"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество на складе"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "price_rrc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Рекомендованная розничная цена",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_infos",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_infos",
                        to="shops.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о товаре",
                "verbose_name_plural": "Информация о товарах",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "shop"), name="unique_product_shop"
                    )
                ],
            },
        ),
    ]
