# Generated by Django 5.2.17 on 2026-09-17 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("phone", "Телефон"), ("address", "Адрес")],
                        max_length=10,
                        verbose_name="Тип контакта",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Телефон"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Улица"
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Дом"
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Корпус"
                    ),
                ),
                (
                    "building",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Строение"
                    ),
                ),
                (
                    "apartment",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Квартира"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
