# Generated by Django 5.2.17 on 2026-09-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Фамилия"
            ),
        ),
    ]
